"""
Subtask 2: DeBERTa-v3-base for 9-Class Evasion with Augmented Data

Trains on augmented evasion dataset (generated by generate_evasion_data.py).
Features:
- DeBERTa-v3-base with boolean features (affirmative_questions, multiple_questions)
- Focal loss (gamma=2.5) with inverse-frequency alpha
- Synthetic sample weighting via --synthetic_weight
- LLRD, gradient accumulation, cosine scheduling
- Early stopping on macro F1
"""

from datasets import load_from_disk
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from transformers import (
 AutoTokenizer,
 AutoModel,
 get_cosine_schedule_with_warmup
)
from sklearn.metrics import classification_report, accuracy_score, f1_score
from tqdm import tqdm
import time
import argparse

print("="*80)
print("SUBTASK 2: DeBERTa-v3-base + Augmented Data for 9-Class Evasion")
print("="*80)

parser = argparse.ArgumentParser(description='DeBERTa-base evasion with augmented data')
parser.add_argument('--data_dir', type=str, default='./QEvasion_evasion_augmented',
 help='Path to augmented dataset')
parser.add_argument('--learning_rate', type=float, default=3e-5)
parser.add_argument('--batch_size', type=int, default=8)
parser.add_argument('--gradient_accumulation_steps', type=int, default=4)
parser.add_argument('--num_epochs', type=int, default=8)
parser.add_argument('--warmup_ratio', type=float, default=0.15)
parser.add_argument('--weight_decay', type=float, default=0.01)
parser.add_argument('--llrd_alpha', type=float, default=0.9)
parser.add_argument('--max_length', type=int, default=512)
parser.add_argument('--focal_gamma', type=float, default=2.5)
parser.add_argument('--patience', type=int, default=4)
parser.add_argument('--synthetic_weight', type=float, default=0.5,
 help='Loss weight for synthetic samples (1.0 = equal to original)')

args = parser.parse_args()

LEARNING_RATE = args.learning_rate
BATCH_SIZE = args.batch_size
GRADIENT_ACCUMULATION_STEPS = args.gradient_accumulation_steps
NUM_EPOCHS = args.num_epochs
WARMUP_RATIO = args.warmup_ratio
WEIGHT_DECAY = args.weight_decay
LLRD_ALPHA = args.llrd_alpha
MAX_LENGTH = args.max_length
FOCAL_GAMMA = args.focal_gamma
PATIENCE = args.patience
SYNTHETIC_WEIGHT = args.synthetic_weight

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"\nDevice: {device}")
if torch.cuda.is_available():
 print(f"GPU: {torch.cuda.get_device_name(0)}")
 print(f"Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

print(f"\n{'='*80}")
print("HYPERPARAMETERS")
print(f"{'='*80}")
print(f"Data dir: {args.data_dir}")
print(f"Learning Rate: {LEARNING_RATE}")
print(f"Batch Size: {BATCH_SIZE}")
print(f"Gradient Accumulation: {GRADIENT_ACCUMULATION_STEPS}")
print(f"Effective Batch Size: {BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS}")
print(f"Max Epochs: {NUM_EPOCHS}")
print(f"Warmup Ratio: {WARMUP_RATIO:.1%}")
print(f"Weight Decay: {WEIGHT_DECAY}")
print(f"LLRD Alpha: {LLRD_ALPHA}")
print(f"Patience: {PATIENCE}")
print(f"Max Length: {MAX_LENGTH}")
print(f"Focal Gamma: {FOCAL_GAMMA}")
print(f"Synthetic Weight: {SYNTHETIC_WEIGHT}")

# Load dataset
print("\n[1/9] Loading augmented dataset...")
dataset = load_from_disk(args.data_dir)
train_df = pd.DataFrame(dataset['train'])
test_df = pd.DataFrame(dataset['test'])

print(f"Training samples: {len(train_df)}")
print(f"Test samples: {len(test_df)}")

# Check for synthetic flag
if 'is_synthetic' in train_df.columns:
 n_synthetic = train_df['is_synthetic'].sum()
 n_original = len(train_df) - n_synthetic
 print(f" Original: {n_original}")
 print(f" Synthetic: {n_synthetic}")
else:
 train_df['is_synthetic'] = False

# Prepare text
print("\n[2/9] Preparing text and features...")

def prepare_text_transformer(row):
 question = row['question']
 answer = row['interview_answer']
 return f"Question: {question} [SEP] Answer: {answer}"

train_df['text'] = train_df.apply(prepare_text_transformer, axis=1)
test_df['text'] = test_df.apply(prepare_text_transformer, axis=1)

def extract_boolean_features(row):
 return [
 float(row['affirmative_questions']) if pd.notna(row.get('affirmative_questions')) else 0.0,
 float(row['multiple_questions']) if pd.notna(row.get('multiple_questions')) else 0.0,
 ]

train_df['bool_features'] = train_df.apply(extract_boolean_features, axis=1)
test_df['bool_features'] = test_df.apply(extract_boolean_features, axis=1)

print(f"Boolean feature dimension: 2")

# Create label mapping for 9 evasion classes
print("\n[3/9] Preparing 9-class evasion labels...")

evasion_labels_raw = train_df['evasion_label'].unique()
label_list = sorted(evasion_labels_raw)

print(f"Found {len(label_list)} evasion classes:")
for i, label in enumerate(label_list, 1):
 count = (train_df['evasion_label'] == label).sum()
 print(f" {i}. {label}: {count} samples ({count/len(train_df)*100:.1f}%)")

label2id = {label: idx for idx, label in enumerate(label_list)}
id2label = {idx: label for label, idx in label2id.items()}

train_df['label_id'] = train_df['evasion_label'].map(label2id)
test_df['label_id'] = 0 # Dummy for test set

print(f"\nLabel mapping: {label2id}")

# Calculate class weights for focal loss
class_counts = train_df['label_id'].value_counts().sort_index()
total = len(train_df)
focal_alpha = torch.tensor([1.0 / (count / total) for count in class_counts],
 dtype=torch.float).to(device)
focal_alpha = focal_alpha / focal_alpha.sum() * len(focal_alpha)

print(f"\nClass distribution and Focal Loss weights:")
for idx in range(len(label_list)):
 label = id2label[idx]
 count = class_counts[idx]
 weight = focal_alpha[idx].item()
 print(f" {idx}. {label:25s}: {count:4d} ({count/total*100:5.1f}%) | weight: {weight:.3f}")

# Compute per-sample weights for synthetic downweighting
sample_weights = []
for _, row in train_df.iterrows():
 if row.get('is_synthetic', False):
 sample_weights.append(SYNTHETIC_WEIGHT)
 else:
 sample_weights.append(1.0)
sample_weights = torch.tensor(sample_weights, dtype=torch.float)

# ============================================================================
# Focal Loss
# ============================================================================
class FocalLoss(nn.Module):
 def __init__(self, alpha=None, gamma=2.5, reduction='mean'):
 super(FocalLoss, self).__init__()
 self.alpha = alpha
 self.gamma = gamma
 self.reduction = reduction

 def forward(self, logits, targets):
 ce_loss = nn.functional.cross_entropy(logits, targets, reduction='none')
 p_t = torch.exp(-ce_loss)
 focal_term = (1 - p_t) ** self.gamma

 if self.alpha is not None:
 alpha_t = self.alpha[targets]
 focal_loss = alpha_t * focal_term * ce_loss
 else:
 focal_loss = focal_term * ce_loss

 if self.reduction == 'mean':
 return focal_loss.mean()
 elif self.reduction == 'sum':
 return focal_loss.sum()
 else:
 return focal_loss

# ============================================================================
# Model
# ============================================================================
class DeBERTaWithFeatures(nn.Module):
 def __init__(self, model_name, num_labels, bool_feature_dim):
 super(DeBERTaWithFeatures, self).__init__()
 self.deberta = AutoModel.from_pretrained(model_name)
 self.config = self.deberta.config
 hidden_size = self.config.hidden_size

 self.feature_processor = nn.Sequential(
 nn.Linear(bool_feature_dim, 16),
 nn.ReLU(),
 nn.Dropout(0.1)
 )

 self.classifier = nn.Sequential(
 nn.Dropout(0.1),
 nn.Linear(hidden_size + 16, num_labels)
 )

 def forward(self, input_ids, attention_mask, bool_features):
 outputs = self.deberta(input_ids=input_ids, attention_mask=attention_mask)
 pooled = outputs.last_hidden_state[:, 0, :]
 feature_embed = self.feature_processor(bool_features)
 combined = torch.cat([pooled, feature_embed], dim=1)
 logits = self.classifier(combined)
 return logits

# ============================================================================
# Dataset
# ============================================================================
class EvasionDatasetWithFeatures(Dataset):
 def __init__(self, texts, labels, bool_features, tokenizer, max_length=512,
 sample_weights=None):
 self.texts = texts
 self.labels = labels
 self.bool_features = bool_features
 self.tokenizer = tokenizer
 self.max_length = max_length
 self.sample_weights = sample_weights

 def __len__(self):
 return len(self.texts)

 def __getitem__(self, idx):
 text = str(self.texts[idx])
 label = self.labels[idx]
 bool_feat = self.bool_features[idx]

 encoding = self.tokenizer(
 text,
 max_length=self.max_length,
 padding='max_length',
 truncation=True,
 return_tensors='pt'
 )

 item = {
 'input_ids': encoding['input_ids'].flatten(),
 'attention_mask': encoding['attention_mask'].flatten(),
 'bool_features': torch.tensor(bool_feat, dtype=torch.float),
 'labels': torch.tensor(label, dtype=torch.long),
 }

 if self.sample_weights is not None:
 item['sample_weight'] = self.sample_weights[idx]

 return item

# ============================================================================
# LLRD
# ============================================================================
def get_optimizer_grouped_parameters(model, learning_rate, weight_decay, llrd_alpha):
 no_decay = ["bias", "LayerNorm.weight"]
 num_layers = model.config.num_hidden_layers

 optimizer_grouped_parameters = []

 # Embeddings
 optimizer_grouped_parameters.append({
 "params": [p for n, p in model.deberta.embeddings.named_parameters()
 if not any(nd in n for nd in no_decay)],
 "weight_decay": weight_decay,
 "lr": learning_rate * (llrd_alpha ** (num_layers + 1))
 })
 optimizer_grouped_parameters.append({
 "params": [p for n, p in model.deberta.embeddings.named_parameters()
 if any(nd in n for nd in no_decay)],
 "weight_decay": 0.0,
 "lr": learning_rate * (llrd_alpha ** (num_layers + 1))
 })

 # Encoder layers
 for layer_idx in range(num_layers):
 layer = model.deberta.encoder.layer[layer_idx]
 layer_lr = learning_rate * (llrd_alpha ** (num_layers - layer_idx))

 optimizer_grouped_parameters.append({
 "params": [p for n, p in layer.named_parameters()
 if not any(nd in n for nd in no_decay)],
 "weight_decay": weight_decay,
 "lr": layer_lr
 })
 optimizer_grouped_parameters.append({
 "params": [p for n, p in layer.named_parameters()
 if any(nd in n for nd in no_decay)],
 "weight_decay": 0.0,
 "lr": layer_lr
 })

 # Feature processor
 optimizer_grouped_parameters.append({
 "params": [p for n, p in model.feature_processor.named_parameters()
 if not any(nd in n for nd in no_decay)],
 "weight_decay": weight_decay,
 "lr": learning_rate
 })
 optimizer_grouped_parameters.append({
 "params": [p for n, p in model.feature_processor.named_parameters()
 if any(nd in n for nd in no_decay)],
 "weight_decay": 0.0,
 "lr": learning_rate
 })

 # Classifier head
 optimizer_grouped_parameters.append({
 "params": [p for n, p in model.classifier.named_parameters()
 if not any(nd in n for nd in no_decay)],
 "weight_decay": weight_decay,
 "lr": learning_rate
 })
 optimizer_grouped_parameters.append({
 "params": [p for n, p in model.classifier.named_parameters()
 if any(nd in n for nd in no_decay)],
 "weight_decay": 0.0,
 "lr": learning_rate
 })

 return optimizer_grouped_parameters

# ============================================================================
# Training / Eval functions
# ============================================================================
def train_epoch(model, dataloader, optimizer, scheduler, device, focal_loss,
 gradient_accumulation_steps, use_sample_weights=False):
 model.train()
 total_loss = 0
 predictions = []
 true_labels = []

 optimizer.zero_grad()

 progress_bar = tqdm(dataloader, desc="Training")
 for step, batch in enumerate(progress_bar):
 input_ids = batch['input_ids'].to(device)
 attention_mask = batch['attention_mask'].to(device)
 bool_features = batch['bool_features'].to(device)
 labels = batch['labels'].to(device)

 logits = model(input_ids=input_ids, attention_mask=attention_mask,
 bool_features=bool_features)

 if use_sample_weights and 'sample_weight' in batch:
 # Per-sample weighted focal loss
 ce_loss = nn.functional.cross_entropy(logits, labels, reduction='none')
 p_t = torch.exp(-ce_loss)
 focal_term = (1 - p_t) ** focal_loss.gamma

 if focal_loss.alpha is not None:
 alpha_t = focal_loss.alpha[labels]
 fl = alpha_t * focal_term * ce_loss
 else:
 fl = focal_term * ce_loss

 sw = batch['sample_weight'].to(device)
 loss = (fl * sw).mean()
 else:
 loss = focal_loss(logits, labels)

 loss = loss / gradient_accumulation_steps
 loss.backward()

 if (step + 1) % gradient_accumulation_steps == 0:
 torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
 optimizer.step()
 scheduler.step()
 optimizer.zero_grad()

 total_loss += loss.item() * gradient_accumulation_steps

 preds = torch.argmax(logits, dim=1)
 predictions.extend(preds.cpu().numpy())
 true_labels.extend(labels.cpu().numpy())

 progress_bar.set_postfix({'loss': f'{loss.item() * gradient_accumulation_steps:.4f}'})

 avg_loss = total_loss / len(dataloader)
 f1 = f1_score(true_labels, predictions, average='macro')

 return avg_loss, f1

def eval_epoch(model, dataloader, device, focal_loss):
 model.eval()
 total_loss = 0
 predictions = []
 true_labels = []

 with torch.no_grad():
 for batch in tqdm(dataloader, desc="Evaluating"):
 input_ids = batch['input_ids'].to(device)
 attention_mask = batch['attention_mask'].to(device)
 bool_features = batch['bool_features'].to(device)
 labels = batch['labels'].to(device)

 logits = model(input_ids=input_ids, attention_mask=attention_mask,
 bool_features=bool_features)

 loss = focal_loss(logits, labels)
 total_loss += loss.item()

 preds = torch.argmax(logits, dim=1)
 predictions.extend(preds.cpu().numpy())
 true_labels.extend(labels.cpu().numpy())

 avg_loss = total_loss / len(dataloader)
 accuracy = accuracy_score(true_labels, predictions)
 f1 = f1_score(true_labels, predictions, average='macro')

 return avg_loss, accuracy, f1, predictions, true_labels

# ============================================================================
# Main Training Loop
# ============================================================================
print("\n[4/9] Initializing tokenizer and model...")
model_name = 'microsoft/deberta-v3-base'
tokenizer = AutoTokenizer.from_pretrained(model_name)

model = DeBERTaWithFeatures(
 model_name=model_name,
 num_labels=len(label_list),
 bool_feature_dim=2
)
model = model.to(device)

print(f"Model: {model_name}")
print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")
print(f"Output: {len(label_list)} evasion classes")

print("\n[5/9] Creating datasets and dataloaders...")
use_sample_weights = SYNTHETIC_WEIGHT < 1.0

train_dataset = EvasionDatasetWithFeatures(
 texts=train_df['text'].tolist(),
 labels=train_df['label_id'].tolist(),
 bool_features=train_df['bool_features'].tolist(),
 tokenizer=tokenizer,
 max_length=MAX_LENGTH,
 sample_weights=sample_weights if use_sample_weights else None
)

test_dataset = EvasionDatasetWithFeatures(
 texts=test_df['text'].tolist(),
 labels=test_df['label_id'].tolist(),
 bool_features=test_df['bool_features'].tolist(),
 tokenizer=tokenizer,
 max_length=MAX_LENGTH
)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

print(f"Train batches: {len(train_loader)}")
print(f"Test batches: {len(test_loader)}")

print("\n[6/9] Setting up optimizer and scheduler...")
optimizer_grouped_parameters = get_optimizer_grouped_parameters(
 model, LEARNING_RATE, WEIGHT_DECAY, LLRD_ALPHA
)
optimizer = torch.optim.AdamW(optimizer_grouped_parameters)

num_training_steps = len(train_loader) * NUM_EPOCHS // GRADIENT_ACCUMULATION_STEPS
num_warmup_steps = int(num_training_steps * WARMUP_RATIO)
scheduler = get_cosine_schedule_with_warmup(
 optimizer,
 num_warmup_steps=num_warmup_steps,
 num_training_steps=num_training_steps
)

print(f"Total training steps: {num_training_steps}")
print(f"Warmup steps: {num_warmup_steps}")

focal_loss = FocalLoss(alpha=focal_alpha, gamma=FOCAL_GAMMA)
print(f"Focal Loss initialized (gamma={FOCAL_GAMMA})")

print("\n[7/9] Training model...")
print("="*80)

best_f1 = 0
best_epoch = 0
patience_counter = 0
start_time = time.time()

for epoch in range(NUM_EPOCHS):
 print(f"\nEpoch {epoch + 1}/{NUM_EPOCHS}")
 print("-" * 80)

 train_loss, train_f1 = train_epoch(
 model, train_loader, optimizer, scheduler, device, focal_loss,
 GRADIENT_ACCUMULATION_STEPS, use_sample_weights=use_sample_weights
 )

 val_loss, val_accuracy, val_f1, val_preds, val_labels = eval_epoch(
 model, test_loader, device, focal_loss
 )

 print(f"\nTrain Loss: {train_loss:.4f} | Train F1: {train_f1:.4f}")
 print(f"Val Loss: {val_loss:.4f} | Val Accuracy: {val_accuracy:.4f} | Val F1: {val_f1:.4f}")

 if val_f1 > best_f1:
 best_f1 = val_f1
 best_epoch = epoch + 1
 patience_counter = 0

 torch.save(model.state_dict(), 'deberta_evasion_augmented_best.pt')
 print(f"New best F1. Saved model.")
 else:
 patience_counter += 1
 print(f"No improvement ({patience_counter}/{PATIENCE})")

 if patience_counter >= PATIENCE:
 print(f"\nEarly stopping triggered after {epoch + 1} epochs")
 break

training_time = time.time() - start_time
print("\n" + "="*80)
print(f"Training complete. Best F1: {best_f1:.4f} (Epoch {best_epoch})")
print(f"Training time: {training_time/60:.1f} minutes")
print("="*80)

# Load best model for final predictions on test set
print("\n[8/9] Loading best model for predictions...")
model.load_state_dict(torch.load('deberta_evasion_augmented_best.pt'))

model.eval()
test_predictions = []

with torch.no_grad():
 for batch in tqdm(test_loader, desc="Predicting"):
 input_ids = batch['input_ids'].to(device)
 attention_mask = batch['attention_mask'].to(device)
 bool_features = batch['bool_features'].to(device)

 logits = model(input_ids=input_ids, attention_mask=attention_mask,
 bool_features=bool_features)

 preds = torch.argmax(logits, dim=1)
 test_predictions.extend(preds.cpu().numpy())

# Map dataset labels to Codabench submission labels
submission_label_map = {
 'Claims ignorance': 'Ignorance',
 'Clarification': 'Clarification',
 'Declining to answer': 'Declining',
 'Deflection': 'Deflection',
 'Dodging': 'Dodging',
 'Explicit': 'Explicit',
 'General': 'General',
 'Implicit': 'Implicit',
 'Partial/half-answer': 'Partial',
}

pred_labels_text = [submission_label_map[id2label[pred]] for pred in test_predictions]
pred_distribution = pd.Series(pred_labels_text).value_counts()
print("\nPrediction distribution on test set:")
for label, count in pred_distribution.items():
 print(f" {label:25s}: {count:3d} ({count/len(test_predictions)*100:5.1f}%)")

# Save predictions
print("\n[9/9] Generating submission file...")
output_file = 'prediction_evasion_augmented'
with open(output_file, 'w') as f:
 for pred_label in pred_labels_text:
 f.write(f"{pred_label}\n")
print(f"Saved predictions: {output_file}")

import zipfile
submission_file = 'submission_evasion_augmented.zip'
with zipfile.ZipFile(submission_file, 'w', zipfile.ZIP_DEFLATED) as zf:
 zf.write(output_file, arcname='prediction')
print(f"Created submission: {submission_file}")

print("\n" + "="*80)
print("TRAINING COMPLETE")
print("="*80)
print(f"Best Validation F1: {best_f1:.4f}")
print(f"Training time: {training_time/60:.1f} minutes")
print(f"Submission file: {submission_file}")
print("="*80)
